from pathlib import Path
from typing import cast

from matplotlib.colors import Colormap
from numpy import uint8
from PIL.Image import Dither, Exif, Image, new, open
from PIL.PngImagePlugin import PngInfo

from ..utils.array import ArrayFloat64

GIF_SUFFIX = ".gif"
PNG_SUFFIX = ".png"
WEBP_SUFFIX = ".webp"

SUPPORTED_SUFFIXES = {GIF_SUFFIX, PNG_SUFFIX, WEBP_SUFFIX}

GENERATED_BY = "Generated by GOES-DL (https://github.com/wvenialbo/GOES-DL/)."


class Animation:

    interval: float
    loop: bool
    filelist: list[Path]
    colormap: Colormap | None

    def __init__(self, fps: float = 3.0, loop: bool = True) -> None:
        self.interval = self._validate_fps(fps)
        self.loop = loop
        self.filelist = []
        self.colormap = None

    def append(self, path: str | Path) -> None:
        self.filelist.append(Path(path))

    def clear(self) -> None:
        self.filelist.clear()

    def extend(self, paths: list[str | Path]) -> None:
        self.filelist.extend([Path(path) for path in paths])

    def remove(self, path: str | Path) -> None:
        path = Path(path)
        if path in self.filelist:
            self.filelist.remove(path)
        else:
            raise ValueError(f"Path '{path}' not found in the file list.")

    def save(self, path: str | Path, overwrite: bool = False) -> None:
        path = self._validate_output_path(path)

        if path.exists() and not overwrite:
            raise ValueError(
                f"File '{path}' already exists, "
                "use `overwrite=True` to overwrite"
            )

        self._create_animation(path)

    def set_colormap(self, colormap: Colormap) -> None:
        self.colormap = colormap

    def set_duration(self, duration: float) -> None:
        self.interval = self._validate_duration(duration)

    def set_filelist(self, filelist: list[str | Path]) -> None:
        if not filelist:
            raise ValueError("`filelist` is empty.")
        self.filelist = [Path(path) for path in filelist]

    def set_fps(self, fps: float) -> None:
        self.interval = self._validate_fps(fps)

    def set_interval(self, interval: float) -> None:
        self.interval = self._validate_interval(interval)

    def set_loop(self, loop: bool) -> None:
        self.loop = loop

    def _build_palette(self) -> bytes | None:
        if self.colormap is None:
            return None

        points = [i / 255 for i in range(256)]
        colors = cast(ArrayFloat64, self.colormap(points))

        colors_rgb = (colors[:, :3] * 255).astype(uint8)
        palette_rgb = colors_rgb.flatten().tolist()

        return bytes(palette_rgb)

    def _create_animation(self, path: Path) -> None:
        images = self._read_images()

        if path.suffix == GIF_SUFFIX:
            self._create_gif_animation(path, images)
        elif path.suffix == PNG_SUFFIX:
            self._create_png_animation(path, images)
        elif path.suffix == WEBP_SUFFIX:
            self._create_webp_animation(path, images)
        else:
            raise ValueError(f"Unexpected format '{path.suffix}'")

    def _create_gif_animation(self, path: Path, images: list[Image]) -> None:
        if not images:
            raise ValueError("Empty image list, cannot create GIF animation")

        first = images[0]
        remaining = images[1:]

        loop_value = 0 if self.loop else 1

        try:
            first.save(
                path,
                save_all=True,
                append_images=remaining,
                optimize=True,
                # >> include_color_table=True,
                # >> palette=0,
                disposal=2,
                loop=loop_value,
                duration=self.interval,
                comment=GENERATED_BY.encode("utf-8"),
            )

        except Exception as error:
            raise ValueError(
                f"Unable to create GIF animation: {error}"
            ) from error

    def _create_png_animation(self, path: Path, images: list[Image]) -> None:
        if not images:
            raise ValueError("Empty image list, cannot create PNG animation")

        first = images[0]
        remaining = images[1:]

        loop_value = 0 if self.loop else 1

        try:
            info = PngInfo()
            info.add_text("Comment", GENERATED_BY.encode("utf-8"))

            first.save(
                path,
                save_all=True,
                append_images=remaining,
                optimize=True,
                loop=loop_value,
                duration=self.interval,
                disposal=0,
                blend=0,
                pnginfo=info,
            )

        except Exception as error:
            raise ValueError(
                f"Unable to create PNG animation: {error}"
            ) from error

    def _create_webp_animation(self, path: Path, images: list[Image]) -> None:
        if not images:
            raise ValueError("Empty image list, cannot create WEBP animation")

        first = images[0]
        remaining = images[1:]

        loop_value = 0 if self.loop else 1

        try:
            user_comment = b"UNICODE\x00" + GENERATED_BY.encode("utf-8")
            exif = Exif()
            exif[37510] = user_comment
            first.save(
                path,
                save_all=True,
                append_images=remaining,
                duration=self.interval,
                loop=loop_value,
                # >> lossless=True,
                # >> quality=100,
                # >> method=6,
                exif=exif.tobytes(),
            )

        except Exception as error:
            raise ValueError(
                f"Unable to create WEBP animation: {error}"
            ) from error

    def _get_palette_image(self) -> Image | None:
        palette = self._build_palette()

        if palette is None:
            return None

        palette_image = new("P", (1, 1))
        palette_image.putpalette(palette)

        return palette_image

    def _read_images(self) -> list[Image]:
        if not self.filelist:
            raise ValueError("File list is empty, cannot create animation")

        palette_image = self._get_palette_image()

        images: list[Image] = []

        for path in self.filelist:
            path = self._validate_frame_path(path)

            try:
                image = open(path).convert("RGB")

                if palette_image:
                    image = image.quantize(
                        palette=palette_image, dither=Dither.FLOYDSTEINBERG
                    )

                images.append(image)

            except OSError as error:
                raise ValueError(
                    f"Error opening image '{path}': {error}"
                ) from error

        return images

    def _validate_duration(self, duration: float) -> float:
        if not self.filelist:
            raise ValueError("File list is empty. Cannot calculate interval.")
        if duration > 0:
            return duration / len(self.filelist)
        raise ValueError(
            f"Invalid duration: Duration must be greater than 0, got {duration}"
        )

    @staticmethod
    def _validate_fps(fps: float) -> float:
        if fps > 0:
            return 1000.0 / fps
        raise ValueError(f"Invalid FPS: FPS must be greater than 0, got {fps}")

    @staticmethod
    def _validate_frame_path(path: Path) -> Path:
        if not path.exists():
            raise ValueError(f"Path '{path}' does not exist")
        if not path.is_file():
            raise ValueError(f"Path '{path}' is not a file")
        return path

    @staticmethod
    def _validate_input_path(path: str | Path) -> Path:
        if not path:
            raise ValueError("`path` is empty")
        return Path(path)

    @staticmethod
    def _validate_interval(interval: float) -> float:
        if interval > 0:
            return interval
        raise ValueError(
            f"Invalid interval: Interval must be greater than 0, got {interval}"
        )

    @staticmethod
    def _validate_output_path(path: str | Path) -> Path:
        if not path:
            raise ValueError("`path` is empty")
        path = Path(path)
        if path == Path():
            raise ValueError("`path` is undefined")
        if path.suffix not in SUPPORTED_SUFFIXES:
            current_suffix = f" '{path.suffix}'" if path.suffix else ""
            supported_formats = "', '".join(SUPPORTED_SUFFIXES)
            raise ValueError(
                f"Unsupported animation format{current_suffix}, "
                f"supported formats are: '{supported_formats}'"
            )
        if path.exists() and not path.is_file():
            raise ValueError(f"Path '{path}' is not a file")
        return path
