name: MyPy

on: [push]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip packages
      uses: actions/cache@v2
      env:
        cache-name: pip-packages-cache
      with:
        path: ~/.cache/pip
        key: ${{ env.cache-name }}-type-check-${{ hashFiles('requirements/frozen/frozen_type_check_requirements.txt') }}
        restore-keys: |
          ${{ env.cache-name }}-type-check-
          ${{ env.cache-name }}-
    - name: Cache mypy cache
      uses: AustinScola/mypy-cache-github-action@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade mypy
        pip install -r requirements.txt
    - name: Install mypy type stubs
      run: |
        mypy --install-types
        pip install --upgrade types-requests
    - name: Analysing the code with mypy
      run: |
        mypy "./src/GOES_DL"
