name: MyPy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade mypy
        mypy --install-types
        pip install --upgrade types-requests
        pip install -r requirements.txt
    - name: Install mypy type stubs
      run: |
        mypy --install-types
    - name: Analysing the code with mypy
      run: |
        mypy "./src/GOES_DL"
